### ISSUE TITLE
Consider using the arch docker container for testing

### ISSUE THREAD

**Issue by jelly** [archlinux/arch-security-tracker#118]
Travisci can run docker containers instead of converting the running container to an Arch one. See the dbscripts travisci for inspiration https://github.com/archlinux/dbscripts/blob/master/.travis.yml

**Comment by anthraxx** [comment]
I don't want a hard dependency on docker to run tests/coverage so if then it could all go into the travis.yml. However, what real improvements would we gain by doing so? The only issue right now is not within the travis-arch we use but most likely withhin a bug in systemd linking.

PS: We don't convert anything. arch-travis does a chroot inside the travis runner (container), so a container in a container, which is basically identical of running docker in a container.

**Comment by jelly** [comment]
Fixed in https://github.com/archlinux/arch-security-tracker/commit/9055e20042bf5fbfdbaa4c6b61f403b64f77bca8
