### ISSUE TITLE
Fix pytest warnings

### ISSUE THREAD

**Issue by jelly** [archlinux/arch-security-tracker#153]
pytest currenty reports a deprecation warning.
```
  /home/jelle/projects/arch-security-tracker/tracker/view/advisory.py:9: DeprecationWarning: 'werkzeug.contrib.atom' is deprecated as of version 0.15 and will be removed in version 1.0.
    from werkzeug.contrib.atom import AtomFeed

-- Docs: https://docs.pytest.org/en/latest/warnings.html
```

**Comment by anthraxx** [comment]
AtomFeed is disabled temporarily as it got dropped from werkzeug and therefor the tracker fails to start

**Comment by ysf** [comment]
All deprecation warnings are now gone and the tests run through with upgraded flask_wtf

**Comment by ysf** [comment]
This is cleared with https://github.com/archlinux/arch-security-tracker/pull/165 and using an upgraded flask_wtf.
