### ISSUE TITLE
Parse NVD json dumps for applicable CVEs

### ISSUE THREAD

**Issue by Foxboron** [archlinux/arch-security-tracker#173]
https://nvd.nist.gov/vuln/data-feeds#JSON_FEED

I reckon the hardest problem is ensuring we parse CPE info for package names.

**Comment by Foxboron** [comment]
I think there should be two views on the tracker for this data.

* One view that parses the recent/modified list and contains the following data
   * CVE
   * pkgname
   * version
   * severity

Obviously the entries needs to be as few false positives as possible. We should also enable easy creation of an AVG group and do some basic matching on `pkgname` and `version` to find existing AVGs.

* One view to search CVEs which are reserved, and not public, so we can have a todolist when details are filled from the recently modified list

**Comment by anthraxx** [comment]
importing remote content is a duplicate of #/141
