### ISSUE TITLE
Re-enable advisory feed

### ISSUE THREAD

**Issue by l0b0** [archlinux/arch-security-tracker#176]
[The feed has been disabled for 11 months](https://github.com/archlinux/arch-security-tracker/commit/8c8c8c4ae4da28fa75f05ff0c9f3619b5a099ad8). Is it possible to fix it? If not, should the link be removed to avoid further [reports](https://bugs.archlinux.org/task/65596)?

**Comment by shibumi** [comment]
werkzeug dropped support for it. If they start supporting it again, we can enable the feed again. The alternative would be another solution for rss feeds that is being supported.

**Comment by Foxboron** [comment]
This is fixed with https://github.com/archlinux/arch-security-tracker/pull/165
