### ISSUE TITLE
Broken routing with Werkzeug 2.2.x

### ISSUE THREAD

**Issue by foutrelis** [archlinux/arch-security-tracker#211]
Kristian noticed last night that CVE links gave 404 errors. Downgrading `python-werkzeug (2.2.2-1 -> 2.1.2-1)` allowed them to work again. Flask version is 2.1.3.

Running `pytest test/test_cve.py::test_show_issue` locally also reproduces the issue with latest Flask 2.2.2 and Werkzeug 2.2.2.

**Comment by anthraxx** [comment]
fixed in e48779936313af83384b6c4602adb5c516bc9612
