### ISSUE TITLE
Add audit logging functionality

### ISSUE THREAD

**Issue by jelly** [archlinux/arch-security-tracker#27]
Add the possibility of logging changes made to advisories and CVE's, so that we can track what has been changed and by whom.

An option is https://sqlalchemy-continuum.readthedocs.io/en/latest/

**Comment by anthraxx** [comment]
- [ ] Log changes to CVE's and Groups bound to specific user
- [ ] Display the change log (history) for those entries
- [ ] Add possibility to revert back a change or to a specific version

**Comment by jelly** [comment]
I've been reading up about sqlalchemy-continuum, this does support versioning for models. But not who changed what, so I'm wondering do we need to add the user as a foreignkey to the CVE model for us to be able to figure out who changed what.

**Comment by anthraxx** [comment]
335c495433534d2e95e2e7adc8815ca439904d0f
