### ISSUE TITLE
Add Content Security Policy

### ISSUE THREAD

**Issue by jelly** [archlinux/arch-security-tracker#40]
Content security policy defines which JavaScript / CSS is allowed to be loaded. The system works based on whitelisting and disallows inline JavaScript and eval() in JavaScript.

References:

https://developers.google.com/web/fundamentals/security/csp/
https://en.wikipedia.org/wiki/Content_Security_Policy
https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

**Comment by jelly** [comment]
@anthraxx would you prefer https://github.com/twaldear/flask-secure-headers or https://github.com/twaldear/flask-csp for implementing this feature? I think the first one would be a bit nicer and more extensive.

Both need to be packaged in the AUR / [community] :)

**Comment by jelly** [comment]
Yet another alternative https://github.com/GoogleCloudPlatform/flask-talisman

**Comment by rgacogne** [comment]
`flask-secure-headers` or `flask-talisman` would also allow us to easily add `X-Frame-Options`, `X-XSS-Protection` and `X-Content-Type-Options` headers, which would be a welcome addition ;)

**Comment by jelly** [comment]
flask-talisman adds X-Frame-Options, X-Content-Type-Options and X-XSS-Protection by default it seems

* Sets X-Frame-Options to SAMEORIGIN to avoid clickjacking.
* Sets X-XSS-Protection to enable a cross site scripting filter for IE/Chrome.
* Sets X-Content-Type-Options to prevents content type sniffing for IE >= 9.

https://github.com/GoogleCloudPlatform/flask-talisman#options

**Comment by SantiagoTorres** [comment]
bump, is this closed by #46
