### ISSUE TITLE
The CVE type in the title of an ASA is not updating.

### ISSUE THREAD

**Issue by shibumi** [archlinux/arch-security-tracker#60]
**Description**

The title in an ASA will not be updated when the type of a CVE is changed after scheduling the ASA. This does affect only ASAs with one CVE. ASAs with multiple CVEs will have 'multiple issues' as type and an update is not necessary.

**How to reproduce:**

1. create one CVE
2. set a specific type
3. create one AVG
4. link the CVE to the AVG
5. schedule an ASA for the AVG
6. change the type in the CVE that's linked to the AVG

the  type will not update in the ASA title. 

**Workaround:** 

un-schedule the ASA, change the CVE type, re-schedule

**Comment by anthraxx** [comment]
duplicate of #51
