### ISSUE TITLE
Display an atom feed icon on the tracker

### ISSUE THREAD

**Issue by jelly** [archlinux/arch-security-tracker#61]
Currently users have to dive in the code and discover that an atom feed exists. Add an icon to the main page which redirects to the atom feed.

**Comment by anthraxx** [comment]
we could use the famfamfam icon for it, but we need to check if we need to add some reference somewhere

**Comment by dopsi** [comment]
You only need to link to the [icons presentation page](http://www.famfamfam.com/lab/icons/silk/) and to the [license](https://creativecommons.org/licenses/by/2.5/) in the credits. 

This may need a new static page or can be as a footer of every page. I think there should be copyright notice on the bottom of every page anyway (like there is on [archlinux.org](https://archlinux.org)).

**Comment by jelly** [comment]
We can also use the official [feed icon](https://en.wikipedia.org/wiki/File:Feed-icon.svg) which is MPL 1.1 licensed (It's from Firefox)
